// src/lib/rajneesh/components/download-button.tsx
import { VoidComponent, Show } from 'solid-js'
import { clx } from '~/utils'
import * as styles from './download-button.css'

export interface DownloadButtonProps {
  /** Whether the track is cached */
  isCached: boolean
  /** Whether download is in progress */
  isDownloading: boolean
  /** Download progress percentage (0-100) */
  progress: number
  /** Click handler for download action */
  onDownload: () => void
  /** Whether to use compact styling */
  compact?: boolean
  /** Additional class name */
  class?: string
}

/**
 * Download button component showing download status and progress.
 * 
 * States:
 * - Not cached: Shows "Download" button
 * - Downloading: Shows "X%" progress
 * - Cached: Shows checkmark badge
 */
export const DownloadButton: VoidComponent<DownloadButtonProps> = (props) => {
  const handleClick = (e: MouseEvent) => {
    e.stopPropagation()
    if (!props.isCached && !props.isDownloading) {
      props.onDownload()
    }
  }

  return (
    <Show
      when={!props.isCached}
      fallback={
        <span class={styles.cachedBadge}>
          <svg class={styles.checkIcon} viewBox="0 0 24 24" fill="currentColor">
            <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
          </svg>
        </span>
      }
    >
      <button
        class={clx(
          styles.downloadButton,
          props.compact && styles.downloadButtonCompact,
          props.class,
        )}
        onClick={handleClick}
        disabled={props.isDownloading}
        title={props.isDownloading ? `Downloading ${props.progress}%` : 'Download for offline'}
      >
        <Show
          when={props.isDownloading}
          fallback={
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z" />
            </svg>
          }
        >
          <svg
            class={styles.spinnerIcon}
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <circle cx="12" cy="12" r="10" opacity="0.25" />
            <path d="M12 2a10 10 0 0 1 10 10" />
          </svg>
          <span class={styles.progressText}>{props.progress}%</span>
        </Show>
      </button>
    </Show>
  )
}

// src/lib/rajneesh/components/DownloadButton.svelte
<script lang="ts">
	import { isRemoteFile, type FileEntity } from '$lib/helpers/file-system.ts'
	import { isUrlCached } from '../cache/audio-cache.ts'
	import { downloadTrack, getDownloadProgressState, initializeDownloadStore } from '../stores/download.svelte.ts'

	interface DownloadButtonProps {
		trackId: string
		file: FileEntity
		class?: string
	}

	const { trackId, file, class: className }: DownloadButtonProps = $props()

	// Initialize the download store
	initializeDownloadStore()

	// Reactive state for cache status
	let isCached = $state(false)

	// Derived state - directly access the reactive store
	const isRemote = $derived(isRemoteFile(file))
	const url = $derived(isRemote ? file.url : '')
	
	// Get progress from reactive state - this creates a proper reactive dependency
	const downloadProgress = $derived(getDownloadProgressState().get(trackId))
	const isDownloading = $derived(
		downloadProgress?.state === 'downloading' || downloadProgress?.state === 'queued'
	)
	const isComplete = $derived(downloadProgress?.state === 'complete')
	const progress = $derived(downloadProgress?.progress ?? 0)

	// Check cache status on mount, when trackId changes, or when download completes
	$effect(() => {
		if (isRemote) {
			// Re-check cache when download completes
			const _ = isComplete
			isUrlCached(file.url).then((cached) => {
				console.log(`[Rajneesh] Cache check for ${trackId}:`, cached)
				isCached = cached
			})
		}
	})

	const handleClick = (e: MouseEvent) => {
		e.stopPropagation()
		e.preventDefault()

		if (!isRemote || isCached || isDownloading) {
			console.log(`[Rajneesh] Download click blocked:`, { isRemote, isCached, isDownloading })
			return
		}

		console.log(`[Rajneesh] Starting download for ${trackId}`)
		downloadTrack(trackId, url)
	}
</script>

{#if isRemote}
	{#if isCached}
		<!-- Cached indicator -->
		<span
			class={[
				'flex size-6 items-center justify-center text-green-500',
				className,
			]}
			title="Downloaded"
		>
			<svg
				width="16"
				height="16"
				viewBox="0 0 24 24"
				fill="currentColor"
			>
				<path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
			</svg>
		</span>
	{:else}
		<!-- Download button -->
		<button
			class={[
				'flex size-8 shrink-0 items-center justify-center rounded-full',
				'hover:bg-surface-container-highest active:bg-surface-container-highest/80',
				'disabled:opacity-50',
				className,
			]}
			onclick={handleClick}
			disabled={isDownloading}
			title={isDownloading ? `Downloading ${progress}%` : 'Download for offline'}
		>
			{#if isDownloading}
				<!-- Progress indicator -->
				<div class="relative flex items-center justify-center">
					<svg
						class="size-5 animate-spin"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
					>
						<circle cx="12" cy="12" r="10" class="opacity-25" />
						<path d="M12 2a10 10 0 0 1 10 10" class="opacity-75" />
					</svg>
					<span class="absolute text-[8px] font-medium">{progress}</span>
				</div>
			{:else}
				<!-- Download icon -->
				<svg
					width="18"
					height="18"
					viewBox="0 0 24 24"
					fill="currentColor"
				>
					<path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z" />
				</svg>
			{/if}
		</button>
	{/if}
{/if}
